/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: aTO67+QfV3B4Qp0x4iPVj2E1D7uzU5Ix+e36Da64c1IPL5vOhm/Kxg0zJyYQNN8JzCqnV1GEXseo+EB4kYOijQ==
 */

/* eslint-disable */
// tslint:disable

import DownloadRequest, {DownloadRequest_InsertParameters} from './download_request'
import Identity, {Identity_InsertParameters} from './identity'
import LocalAssetDb, {LocalAssetDb_InsertParameters} from './local_asset_db'

interface DatabaseSchema {
  download_request: {record: DownloadRequest, insert: DownloadRequest_InsertParameters};
  identity: {record: Identity, insert: Identity_InsertParameters};
  local_asset_db: {record: LocalAssetDb, insert: LocalAssetDb_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "identity" && c === "vc") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  DownloadRequest,
  DownloadRequest_InsertParameters,
  Identity,
  Identity_InsertParameters,
  LocalAssetDb,
  LocalAssetDb_InsertParameters,
}
