/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1VAD96++33JtDKin9Ym0EFxWUvLo62cPhHm8ifE6tk95UkS0/GXCPPsOz51/GEGk2ZuWEZYCr8NjM5EzKGRjGQ==
 */

/* eslint-disable */
// tslint:disable

interface LocalAssetDb {
  asset_path: string
  cid: string
  hash_asset: string
  hash_offering: string
  nft_name: string & {readonly __brand?: 'local_asset_db_nft_name'}
  nft_sc_address: (string) | null
  offering_path: string
  sign: string
}
export default LocalAssetDb;

interface LocalAssetDb_InsertParameters {
  asset_path: string
  cid: string
  hash_asset: string
  hash_offering: string
  nft_name: string & {readonly __brand?: 'local_asset_db_nft_name'}
  nft_sc_address?: (string) | null
  offering_path: string
  sign: string
}
export type {LocalAssetDb_InsertParameters}
