/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UGGGZjCysO4w+nEsO0Ww/iR2sQ2TwIHNNcV0Mh3XSafA8JCYXeDEVHIbIDIM4TBtUCjqWwuk0q/WhNqJ0iSwRw==
 */

/* eslint-disable */
// tslint:disable

interface DownloadRequest {
  h_nonce: string & {readonly __brand?: 'download_request_h_nonce'}
  nft_name: (string) | null
}
export default DownloadRequest;

interface DownloadRequest_InsertParameters {
  h_nonce: string & {readonly __brand?: 'download_request_h_nonce'}
  nft_name?: (string) | null
}
export type {DownloadRequest_InsertParameters}
