/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Y1rejqwX+VpyK0jXf08HHI2ghjHLHso5qqUj6KXrLzwRgiS4adJqKN9DRxA8rYJ9SBu3g3HLmm4KeA34/PDt9w==
 */

/* eslint-disable */
// tslint:disable

interface Identity {
  did: string & {readonly __brand?: 'identity_did'}
  privkey: string
  vc: (any) | null
}
export default Identity;

interface Identity_InsertParameters {
  did: string & {readonly __brand?: 'identity_did'}
  privkey: string
  vc?: (any) | null
}
export type {Identity_InsertParameters}
