/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: KVLrUSM+J5guQDRTzY9uNnrzkupqvAFji3UcUp+tpstnpt0QLmJhukA9OrRqa2rBINdeQIYlS8LAUBHw9u11Xw==
 */

/* eslint-disable */
// tslint:disable

interface Identity {
  did: string & {readonly __brand?: 'identity_did'}
  mnemonic: string
  privkey: string
  pubkey: string
  wallet_address: string
}
export default Identity;

interface Identity_InsertParameters {
  did: string & {readonly __brand?: 'identity_did'}
  mnemonic: string
  privkey: string
  pubkey: string
  wallet_address: string
}
export type {Identity_InsertParameters}
