/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: lmFou+KaatM4xM4AUmjfggR3ev2IaroN1nzZsacpJRgF+ggxLjtZFzzb+85Hw88+5+GuQEzdNzUICN216vYWCg==
 */

/* eslint-disable */
// tslint:disable

import Identity, {Identity_InsertParameters} from './identity'

interface DatabaseSchema {
  identity: {record: Identity, insert: Identity_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Identity,
  Identity_InsertParameters,
}
