/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1+RQgcFAV3Ynr/V3Md+PjEyKsqvaZx3wxqSl4R/olM/znEQDeK8Hn/MN2ZZWbwcDk4C4oaq8VCHmtyXgZSMeLw==
 */

/* eslint-disable */
// tslint:disable

import Identity, {Identity_InsertParameters} from './identity'
import LocalAssetDb, {LocalAssetDb_InsertParameters} from './local_asset_db'

interface DatabaseSchema {
  identity: {record: Identity, insert: Identity_InsertParameters};
  local_asset_db: {record: LocalAssetDb, insert: LocalAssetDb_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "identity" && c === "vc") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  Identity,
  Identity_InsertParameters,
  LocalAssetDb,
  LocalAssetDb_InsertParameters,
}
