/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CLYXHBAg/R+JAsaD39W+Q5YJVsLT6hK47/1XX9KOlJ73X1QS6NwfYrgKttzLvkg3Z9gF7u07Ip5yxi1/74Qdyg==
 */

/* eslint-disable */
// tslint:disable

import Identity, {Identity_InsertParameters} from './identity'

interface DatabaseSchema {
  identity: {record: Identity, insert: Identity_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "identity" && c === "vc") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  Identity,
  Identity_InsertParameters,
}
