/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: XYgHUViWZQzeO137kH64SUbS8N3NDVliJUvvN6sLa7x1NV2aDLWwaHiVWknqH7x71KEw1T3T5mUcoOa6486TcQ==
 */

/* eslint-disable */
// tslint:disable

interface LocalAssetDb {
  asset_path: string
  cid: string
  hash_asset: string
  hash_offering: string
  nft_name: string & {readonly __brand?: 'local_asset_db_nft_name'}
  offering_path: string
  sign: string
}
export default LocalAssetDb;

interface LocalAssetDb_InsertParameters {
  asset_path: string
  cid: string
  hash_asset: string
  hash_offering: string
  nft_name: string & {readonly __brand?: 'local_asset_db_nft_name'}
  offering_path: string
  sign: string
}
export type {LocalAssetDb_InsertParameters}
